import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../core/models/employee.dart';
import '../repositories/hr_repository.dart';

part 'hr_provider.g.dart';

/// Provider for HR Repository
@riverpod
HrRepository hrRepository(HrRepositoryRef ref) {
  return HrRepository();
}

/// Provider to fetch all employees
@riverpod
Future<List<Employee>> hrEmployees(HrEmployeesRef ref) async {
  final repository = ref.watch(hrRepositoryProvider);
  return repository.getEmployees();
}

/// AsyncNotifier for HR actions (create, update, delete)
@riverpod
class HrController extends _$HrController {
  @override
  FutureOr<void> build() {
    // No initial state to load
  }

  Future<bool> checkPinUnique(String pin) async {
    final repository = ref.read(hrRepositoryProvider);
    return repository.checkPinUnique(pin);
  }

  Future<void> createEmployee({
    required String fullName,
    required String pin,
    required String role,
    required DateTime? sanepidExpiry,
    required String venueId, // For future use
    required String zoneId, // For future use
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repository = ref.read(hrRepositoryProvider);
      
      final employee = Employee(
        id: '', // Generated by DB
        fullName: fullName,
        pinHash: '', // Handled by Repo
        role: role,
        isActive: true,
        sanepidExpiry: sanepidExpiry,
      );
      
      await repository.createEmployee(employee, pin);
      // Invalidate list to refresh UI
      ref.invalidate(hrEmployeesProvider);
    });
  }

  Future<void> updateSanepid(String employeeId, DateTime newDate) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repository = ref.read(hrRepositoryProvider);
      await repository.updateSanepid(employeeId, newDate);
      ref.invalidate(hrEmployeesProvider);
    });
  }

  Future<void> toggleActive(String employeeId, bool isActive) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repository = ref.read(hrRepositoryProvider);
      await repository.toggleActive(employeeId, isActive);
      ref.invalidate(hrEmployeesProvider);
    });
  }
}
